# Generated by Django 5.1.4 on 2024-12-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('t', models.FloatField()),
                ('samples', models.IntegerField()),
                ('r_25um', models.FloatField()),
                ('ugm3_25um', models.FloatField()),
                ('pcs_25um', models.FloatField()),
                ('r_1um', models.FloatField()),
                ('ugm3_1um', models.FloatField()),
                ('pcs_1um', models.FloatField()),
            ],
        ),
    ]
