# Generated by Django 5.1.4 on 2024-12-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='humidity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='temp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='pcs_1um',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='pcs_25um',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='r_1um',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='r_25um',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='samples',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='t',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='ugm3_1um',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='ugm3_25um',
            field=models.FloatField(null=True),
        ),
    ]
