# Generated by Django 5.1.4 on 2024-12-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sensordata_humidity_sensordata_temp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='flame',
            field=models.FloatField(null=True),
        ),
    ]
