# Generated by Django 5.1.4 on 2025-01-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sensordata_flame'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='MQ135_AQ',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='MQ5_LPG',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='MQ7_CO',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='MQ8_H2',
            field=models.FloatField(null=True),
        ),
    ]
